service:
  name: edge-madsstorm-dk
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  
provider:
  name: cloudflare 
  
plugins:
  - serverless-cloudflare-workers
  
functions:
  header-manipulation:
    worker: headers
    script: headers
    events:
     - http:
         url: edge.madsstorm.dk/*
         method: GET
