service:
  name: edge-madsstorm-dk
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  
provider:
  name: cloudflare
  environment:
    cloudTranslationApiKey: ${env:CLOUD_TRANSLATION_API_KEY}
  
plugins:
  - serverless-cloudflare-workers
  
functions:
  edge-worker:
    worker: edge-worker
    script: worker
    events:
      - http:
        url: edge.madsstorm.dk/*
        method: GET
    resources:
      kv:
        - variable: kvStorage
            namespace: edgeNamespace