service:
  name: edge-madsstorm-dk
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  
provider:
  name: cloudflare
  
plugins:
  - serverless-cloudflare-workers
  
functions:
  edge-worker:
    script: worker
    environment:
      cloudTranslationApiKey: ${env:CLOUD_TRANSLATION_API_KEY}
    events:
      - http:
          url: edge.madsstorm.dk/*
          method: GET
    resources:
      kv:
        - variable: kvStorage
          namespace: edgeNamespace