service:
  name: edge-madsstorm-dk
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  
provider:
  name: cloudflare 
  
plugins:
  - serverless-cloudflare-workers
  
functions:
  edge.madsstorm.dk:
    worker: edge-madsstorm-dk
    script: worker