service:
  name: edge-madsstorm-dk
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  
provider:
  name: cloudflare 
  
plugins:
  - serverless-cloudflare-workers
  
functions:
  welcome-to-the-edge:
    worker: welcome
    script: welcome
    events:
     - http:
         url: edge.madsstorm.dk/*
         method: GET
  header-manipulation:
    worker: headers
    script: headers
    events:
     - http:
         url: madsstorm.dk/*
         method: GET