service:
  name: edge-madsstorm-dk
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  
provider:
  name: cloudflare 
  
plugins:
  - serverless-cloudflare-workers
  
functions:
  worker:
    worker: worker
    script: worker
    events:
     - http:
         url: edge.madsstorm.dk/*
         method: GET
    resources:
      kv:
        variable: kvStorage
        namespace: edgeMadsstormNamespace
